sudo: required
services:
  - docker
before_install:
  - docker build -t ankitsinghgslab/docker-react -f Dockerfile.dev

#run tests before deploying to the server
#using -- --coverage to exit with code 0 otherwise throw error
script:
  - docker run ankitsinghgslab/docker-react npm run test -- --coverage

#automatic deployment code using travis CI
# deploy:
#   provider: elasticbeanstalk #aws elasticbeanstalk service
#   region: "us-west-2" #region of the web services provider you are using
#   app: "docker" #app name in aws
#   env: "Docker-env" #environment created by elasticbeanstalk
#   bucket_name: "elasticbeanstalk-us-west-2-30101010" #search bucket name from s3 service (AWS)
#   bucket_path: "docker" #same as app name
#   on:
#    branch: master #specify branch for CI/CD pipelines

#   access_key_id: "$ACCESS_KEY_VARIABLE" #store varible securely in environment
#   secret_access_key:
#     secure: "$SECRET_ACCESS_KEY_VARIABLE" #store varible securely in environment